services:

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        WWWUSER: 1000
        WWWGROUP: 1000
    container_name: ez-php-session-app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: ez-php-session-redis
    ports:
      - "${REDIS_HOST_PORT:-6387}:6379"
